### ISSUE TITLE
More robust date parsing for trending

### ISSUE THREAD

**Issue by mchamberland** [cutright/IMRT-QA-Data-Miner#7]
[https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/trending_arccheck.py#L111](url)

SNC Patient software actually allows two date formats for the PDF reports:
`<month>/<day>/<year>`
`<day>/<month>/<year>`

The easiest way to deal with this would be to enforce one format, but the nice thing would be to offer an option to the user.

Also, there are some sanity checks that could be done.

**Comment by cutright** [comment]
I think I'll have better luck using `dateutil.parser.parse()`

```
from dateutil.parser import parse
parse('5/30/2018')
datetime.datetime(2018, 5, 30, 0, 0)
parse('30/05/2018')
datetime.datetime(2018, 5, 30, 0, 0)
parse('2018/5/30')
datetime.datetime(2018, 5, 30, 0, 0)
parse('2018/30/5')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\dcutright\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\dcutright\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 654, in parse
    ret = self._build_naive(res, default)
  File "C:\Users\dcutright\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 1229, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12
```
